language: 
    - r
    - cpp

bioc_required: true

sudo: required

r_packages:
    - rmarkdown

env:
 global:
   - BIOC_USE_DEVEL="TRUE"       

r_github_packages:
    - jimhester/covr

after_success:
    - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    recipients:
      - jacobcvt12@gmail.com
    on_success: always
    on_failure: always
