language: c

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap

install:
    - ./travis-tool.sh install_bioc_deps  

script: ./travis-tool.sh run_tests

env:
 global:
   - BIOC_USE_DEVEL="TRUE"       

#r_packages:
    #- rmarkdown

#r_github_packages:
    #- jimhester/covr

#after_success:
    #- Rscript -e 'library(covr);codecov()'

notifications:
  email:
    recipients:
      - jacobcvt12@gmail.com
      - rscharpf@jhu.edu      
    on_success: always
    on_failure: always
