language: 
    - r
    - cpp

bioc_required: true

sudo: required

r_packages:
    - rmarkdown

r_github_packages:
    - jimhester/covr

bioc_packages:
    - BiocGenerics
    - BiocStyle
    - BSgenome.Hsapiens.UCSC.hg19
    - GenomeInfoDb
    - GenomicRanges
    - IRanges
    - oligoClasses
    - S4Vectors
    - VanillaICE
    - BiocInstaller

after_success:
    - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    recipients:
      - jacobcvt12@gmail.com
    on_success: always
    on_failure: always
